export const nationalities = [
  { value: 'AU', label: 'Australia' },
  { value: 'BR', label: 'Brasil' },
  { value: 'CA', label: 'Canadá' },
  { value: 'CH', label: 'Suiza' },
  { value: 'DE', label: 'Alemania' },
  { value: 'DK', label: 'Dinamarca' },
  { value: 'ES', label: 'España' },
  { value: 'FI', label: 'Finlandia' },
  { value: 'FR', label: 'Francia' },
  { value: 'GB', label: 'Reino Unido' },
  { value: 'IE', label: 'Irlanda' },
  { value: 'IN', label: 'India' },
  { value: 'IR', label: 'Irán' },
  { value: 'MX', label: 'México' },
  { value: 'NL', label: 'Países Bajos' },
  { value: 'NO', label: 'Noruega' },
  { value: 'NZ', label: 'Nueva Zelanda' },
  { value: 'RS', label: 'Serbia' },
  { value: 'TR', label: 'Turquía' },
  { value: 'UA', label: 'Ucrania' },
  { value: 'US', label: 'Estados Unidos' },
];
